name:                positive
version:             0.1.0.0
github:              "rl-king/positive"
license:             BSD3
author:              "Ruben Lie King"
maintainer:          "hello@rubenlieking.com"
copyright:           "BSD-3"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rl-king/positive#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - filepath
  - hip
  - http-media
  - http-types
  - massiv
  - massiv-io
  - servant
  - servant-server
  - stm
  - text
  - wai
  - warp

library:
  source-dirs: src/backend

executables:
  positive-exe:
    main:                Main.hs
    source-dirs:         src/backend/app
    dependencies:
    - positive
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  positive-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - positive
