name: positive
version: 0.1.0.0
github: "rl-king/positive"
license: BSD3
author: "Ruben Lie King"
maintainer: "hello@rubenlieking.com"
copyright: "BSD-3"

extra-source-files:
  - README.md
description: Please see the README on GitHub at <https://github.com/rl-king/positive#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - base64-bytestring
  - bound
  - bytestring
  - deepseq
  - directory
  - elm-syntax
  - fast-logger
  - filepath
  - file-embed
  - fused-effects == 1.1.1.1
  - generics-sop
  - Glob
  - hashable
  - haskeline
  - haskell-to-elm
  - hasql
  - hasql-pool
  - hasql-th
  - hasql-transaction
  - hip
  - http-media
  - http-types
  - massiv
  - megaparsec
  - massiv-io
  - optparse-applicative
  - process
  - profunctors
  - psqueues
  - record-hasfield
  - safe-exceptions
  - servant
  - servant-server
  - servant-to-elm
  - text
  - time
  - transformers
  - vector
  - wai
  - wai-extra
  - wai-app-static
  - warp
  - unordered-containers

library:
  source-dirs: src/backend

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude

executables:
  pos:
    main: Main.hs
    source-dirs: src/backend/app
    dependencies:
      - positive
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -fno-warn-name-shadowing
  codegen:
    main: Main.hs
    source-dirs: src/backend/codegen
    dependencies:
      - positive
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - positive
      - hspec
      - hspec-expectations

benchmarks:
  pos-benchmark:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - base
      - positive
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -O2
