name:                positive
version:             0.1.0.0
github:              "rl-king/positive"
license:             BSD3
author:              "Ruben Lie King"
maintainer:          "hello@rubenlieking.com"
copyright:           "BSD-3"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rl-king/positive#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - base64-bytestring
  - bytestring
  - directory
  - elm-syntax
  - fast-logger
  - filepath
  - file-embed
  - generics-sop
  - Glob
  - haskeline
  - haskell-to-elm
  - hip
  - http-media
  - http-types
  - massiv
  - massiv-io
  - mtl
  - optparse-applicative
  - process
  - record-hasfield
  - safe-exceptions
  - servant
  - servant-server
  - servant-to-elm
  - text
  - time
  - vector
  - wai
  - wai-extra
  - wai-app-static
  - warp
  - unordered-containers

library:
  source-dirs: src/backend

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude

executables:
  pos:
    main:                Main.hs
    source-dirs:         src/backend/app
    dependencies:
    - positive
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
